ServerCode/HealthcareIntervention/Models/BlastResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HealthcareIntervention.Models
{
    public class BlastResponse
    {
        public int BlastResponseId { get; set; }
        public int BlastScheduleId { get; set; }
        public string Response { get; set; }
        public string UserId { get; set; }
        public int StudyId { get; set; }
        public DateTime TimeRead { get; set; }
        public Boolean ReadByNurse { get; set; }
    }
}

ServerCode/HealthcareIntervention/Controllers/BlastResponseController.cs
using HealthcareIntervention.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HealthcareIntervention.Controllers
{
    public class BlastResponseController : Controller
    {
        private static ApplicationDbContext db = new ApplicationDbContext();

        //GET: Load Blast for Patients
        [Authorize(Roles = RoleNames.Volunteer+ "," + RoleNames.Nurse)]
        public static void LoadBlasts()
        {
            DateTime CurrentTime = DateTime.Now;
            var List = db.BlastSchedules.Where(x => x.Visible == false).Where(y => y.SendTime <= CurrentTime).ToList();
            foreach(var item in List)
            {
                item.Visible = true;
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
            }
        }
        // GET: BlastResponse
        [Authorize(Roles = RoleNames.Volunteer)]
        public ActionResult BlastIndexForPatient()
        {
            if (Session["LoggedUserID"] == null)
            {
                return RedirectToAction("SignOff", "Account");
            }
            int StudyId = Convert.ToInt32(Session["StudyId"].ToString());
            string UserID = (Session["LoggedUserID"].ToString());
            var Blasts = db.BlastSchedules.Where(x => x.UserId == UserID).Where(y => y.StudyId == StudyId).Where(z => z.Visible == true).Where(a => a.Responded == false).ToList();
            if (Blasts.Count == 0)
            {
                return View("EmptyBlastListing");
            }
            else
            {
                List<BlastListing> BlastList = new List<BlastListing>();
                
                foreach (var Blast in Blasts.OrderBy(m=>m.SendTime))
                {
                    BlastListing entry = new BlastListing();
                    entry.BlastScheduleId = Blast.BlastScheduleId;
                    entry.BlastName = db.AnnouncementMessages.Find(Blast.AnnouncementMessageId).AnnouncementName.ToString();
                    BlastList.Add(entry);
                }
                return View("BlastListing",BlastList);
            }
           
        }
        [Authorize(Roles = RoleNames.Nurse)]
        public ActionResult BlastIndexForNurses()
        {
            if (Session["LoggedUserID"] == null)
            {
                return RedirectToAction("SignOff", "Account");
            }
            int StudyId = Convert.ToInt32(Session["StudyId"].ToString());
            string UserID = (Session["LoggedUserID"].ToString());
            var Patients = db.PatientStudyMappings.Where(x => x.StudyId == StudyId).ToList();
            List<BlastListingNurseEntries> Listing = new List<BlastListingNurseEntries>();
            foreach(var item in Patients)
            {
                BlastListingNurseEntries entry = new BlastListingNurseEntries();
                var Patient = db.Users.Find(item.PatientId);
                entry.UserName = item.PatientId;
                entry.Name = Patient.FirstName + " " + Patient.LastName;
                entry.unread = db.BlastResponses.Where(x => x.ReadByNurse == false).Where(y => y.UserId == item.PatientId).Where(z => z.StudyId == StudyId).Count();
                Listing.Add(entry);
            }
            return View("BlastListingNurse",Listing.OrderByDescending(m=>m.unread));
        }
        [Authorize(Roles = RoleNames.Nurse)]
        public ActionResult ViewResponse(string id)
        {
            if (Session["LoggedUserID"] == null)
            {
                return RedirectToAction("SignOff", "Account");
            }
            int StudyId = Convert.ToInt32(Session["StudyId"].ToString());
            BlastResponses Response = new BlastResponses();
            Response.Answered = new List<BlastResponseEntry>();
            Response.UnAnswered= new List<BlastResponseEntry>();
            Response.UserId = id;
            var User = db.Users.Find(id);
            ViewBag.Name = User.FirstName + " " + User.LastName;
            var Answered = db.BlastSchedules.Where(x => x.UserId == id).Where(y => y.StudyId == StudyId).Where(z => z.Responded == true).ToList();
            var UnAnswered = db.BlastSchedules.Where(x => x.UserId == id).Where(y => y.StudyId == StudyId).Where(z => z.Responded == false).ToList();

            foreach(var item in Answered)
            {
                BlastResponseEntry MyEntry = new BlastResponseEntry();
                MyEntry.New = false;
                switch (item.BlastType)
                {
                    case "TextOnly":
                        MyEntry.Question = db.BlastTemplateTextOnlies.Where(x => x.AnnouncementMessageId == item.AnnouncementMessageId).First().BlastMessage;
                        MyEntry.SendTime = item.SendTime;
                        break;
                    case "TextWithResponse":
                        MyEntry.Question = db.BlastTemplateTextWithResponses.Where(x => x.AnnouncementMessageId == item.AnnouncementMessageId).First().BlastMessage;
                        MyEntry.SendTime = item.SendTime;
                        var respons = db.BlastResponses.Where(y => y.BlastScheduleId == item.BlastScheduleId).First();
                        if (respons.ReadByNurse == false)
                        {
                            MyEntry.New = true;
                            respons.ReadByNurse = true;
                            db.Entry(respons).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                        MyEntry.Answer = respons.Response;
                        MyEntry.ReadTime = respons.TimeRead;
                        break;
                    case "ChooseOneFromList":
                        MyEntry.Question = db.BlastTemplateOptionsQuestions.Where(x => x.AnnouncementMessageId == item.AnnouncementMessageId).First().Question;
                        MyEntry.SendTime = item.SendTime;
                        var respons1= db.BlastResponses.Where(y => y.BlastScheduleId == item.BlastScheduleId).First();
                        if (respons1.ReadByNurse == false)
                        {
                            MyEntry.New = true;
                            respons1.ReadByNurse = true;
                            db.Entry(respons1).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                        MyEntry.Answer = respons1.Response;
                        MyEntry.ReadTime = respons1.TimeRead;
                        break;
                    case "ChooseSeveralFromList":
                        MyEntry.Question = db.BlastTemplateOptionsQuestions.Where(x => x.AnnouncementMessageId == item.AnnouncementMessageId).First().Question;
                        MyEntry.SendTime = item.SendTime;
                        var respons2 = db.BlastResponses.Where(y => y.BlastScheduleId == item.BlastScheduleId).First();
                        if (respons2.ReadByNurse == false)
                        {
                            MyEntry.New = true;
                            respons2.ReadByNurse = true;
                            db.Entry(respons2).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                        MyEntry.Answer = respons2.Response;
                        MyEntry.ReadTime = respons2.TimeRead;
                        break;
                }
                Response.Answered.Add(MyEntry);                  
            }
            foreach (var item in UnAnswered)
            {
                BlastResponseEntry MyEntry = new BlastResponseEntry();
                switch (item.BlastType)
                {
                    case "TextOnly":
                        MyEntry.Question = db.BlastTemplateTextOnlies.Where(x => x.AnnouncementMessageId == item.AnnouncementMessageId).First().BlastMessage;
                        MyEntry.SendTime = item.SendTime;
                        break;
                    case "TextWithResponse":
                        MyEntry.Question = db.BlastTemplateTextWithResponses.Where(x => x.AnnouncementMessageId == item.AnnouncementMessageId).First().BlastMessage;
                        MyEntry.SendTime = item.SendTime;
                        break;
                    case "ChooseOneFromList":
                        MyEntry.Question = db.BlastTemplateOptionsQuestions.Where(x => x.AnnouncementMessageId == item.AnnouncementMessageId).First().Question;
                        MyEntry.SendTime = item.SendTime;
                        break;
                    case "ChooseSeveralFromList":
                        MyEntry.Question = db.BlastTemplateOptionsQuestions.Where(x => x.AnnouncementMessageId == item.AnnouncementMessageId).First().Question;
                        MyEntry.SendTime = item.SendTime;
                        break;
                }
                Response.UnAnswered.Add(MyEntry);
            }
            Response.Answered = Response.Answered.OrderByDescending(x => x.SendTime).ToList();
            return View("ViewResponse",Response);
        }

        // GET: BlastResponse/Details/5
        [Authorize(Roles = RoleNames.Volunteer)]
        public ActionResult WriteResponse(int? id)
        {
            if (Session["LoggedUserID"] == null)
            {
                return RedirectToAction("SignOff", "Account");
            }

            var message = db.BlastSchedules.Find((int)id);
            if (message != null)
            {

                switch (message.BlastType)
                {
                    case "TextOnly":
                        BlastResponseTextOnly item = new BlastResponseTextOnly();
                        item.BlastScheduleId = message.BlastScheduleId;

ServerCode/HealthcareIntervention/Views/BlastResponse/BlastListing.cshtml
@model IEnumerable<HealthcareIntervention.Models.BlastListing>
    <h2>Blasts</h2>
    <h4>Choose the Blast message you want to respond to</h4>
<table class="table">
    <tr>
        <td>
            @Html.Label("Blast Message")
        </td>
    </tr>
    @foreach(var item in Model)
    {
        <tr>
            <td>
                <a href="@Url.Action("WriteResponse","BlastResponse",new { id=item.BlastScheduleId })">
                    @Html.DisplayFor(modelItem => item.BlastName)
                </a>
            </td>
        </tr>
    }
</table>

ServerCode/HealthcareIntervention/Views/BlastResponse/BlastListingNurse.cshtml
@model IEnumerable<HealthcareIntervention.Models.BlastListingNurseEntries>

@{
    ViewBag.Title = "Index";
}

<h2>Patients in the study</h2>


<table class="table">

    <tr>
        <th>
            @Html.Label("Name")
        </th>
        <th>
            @Html.Label("Unread Blasts")
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="@Url.Action("ViewResponse","BlastResponse",new { id=item.UserName })">
                    @Html.DisplayFor(modelItem => item.Name)
                </a>
                
            </td>
            <td>
                @Html.DisplayFor(m => item.unread)
            </td>
        </tr>
    }

</table>



ServerCode/HealthcareIntervention/Views/BlastResponse/ChooseManyOption.cshtml
@model HealthcareIntervention.Models.BlastResponseSelectMany
<h2>Blast Message</h2>
@using (Html.BeginForm("ChooseManyOption", "BlastResponse", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="table-bordered table">
        @Html.HiddenFor(m => m.BlastScheduleId)
        @Html.DisplayFor(m => m.Question)
    </div>
    <div class="tab-content ">
        @for(var i = 0; i < Model.Options.Count(); i++)
        {
            <div class="list-inline">
                <div class="checkbox">
                    @Html.EditorFor(m => Model.Options[i].Selection)
                    @Html.DisplayFor(m=>Model.Options[i].Text)
                    @Html.HiddenFor(m=>Model.Options[i].Text)
                </div>
            </div>
        }
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Done" class="btn btn-default" />
        </div>
    </div>
}


ServerCode/HealthcareIntervention/Views/BlastResponse/ChooseOneOption.cshtml
@model HealthcareIntervention.Models.BlastResponseChooseOne
<h2>Blast Message</h2>
@using (Html.BeginForm("ChooseOneOption", "BlastResponse", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="table-bordered table">
        @Html.HiddenFor(m => m.BlastScheduleId)
        @Html.DisplayFor(m => m.Question)
    </div>
    <div class="tab-content ">
       @foreach(var item in Model.Responses)
       {
           <div class="list-inline">
               @Html.RadioButtonFor(m => m.Response, item)
               @Html.Label(item)
           </div>        
       }
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Done" class="btn btn-default" />
        </div>
    </div>
}

ServerCode/HealthcareIntervention/Views/BlastResponse/EmptyBlastListing.cshtml
<h2>Nothing right now!</h2>
<h4>There are no Blast messages to respond now. Please check back later</h4>

ServerCode/HealthcareIntervention/Views/BlastResponse/TextOnly.cshtml
@model HealthcareIntervention.Models.BlastResponseTextOnly
<h2>Blast Message</h2>
@using (Html.BeginForm("BlastResponseTextOnly", "BlastResponse", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
@Html.AntiForgeryToken()
    <div class="table-bordered table">
        @Html.HiddenFor(m => m.BlastScheduleId)
        @Html.DisplayFor(m => m.Text)
     </div>
     <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Done" class="btn btn-default" />
            </div>
     </div>
}

ServerCode/HealthcareIntervention/Views/BlastResponse/TextWithResponse.cshtml
@model HealthcareIntervention.Models.BlastResponseTextWithResponse
<h2>Blast Message</h2>
@using (Html.BeginForm("BlastResponseTextWithReply", "BlastResponse", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="table-bordered table">
        @Html.HiddenFor(m => m.BlastScheduleId)
        @Html.DisplayFor(m => m.Text)       
    </div>
    <div class="tab-content">
        @Html.TextAreaFor(m => m.Response,5, 100,null)
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Done" class="btn btn-default" />
        </div>
    </div>
}


ServerCode/HealthcareIntervention/Views/BlastResponse/ViewResponse.cshtml
@model HealthcareIntervention.Models.BlastResponses
    <h2>Blast Response</h2>
<h4>@ViewBag.Name</h4>
@Html.ActionLink("Message me","Index","Messages", new { id = Model.UserId },null)
<div>
    
    <hr />
<div class="tab-pane">
    <h4 class="text-info">Responded</h4>
    @if (Model.Answered.Count == 0)
    {
        @Html.Label("No responses yet!")
    }
    @foreach (var item in Model.Answered)
    {      <div class="table-bordered">
               <div class="label-default ">
                   <span class="glyphicon glyphicon-question-sign "></span>
                   @Html.DisplayFor(m => item.Question)
                   @if (item.New == true)
                   {
                       @Html.Label("New", htmlAttributes: new { @class = "text-danger" })
                   }
                   <br />
                   @Html.DisplayFor(m => item.SendTime)
               </div>
         @if (item.Answer != null)
            {
                <div>
                    @Html.DisplayFor(m => item.Answer)<br />
                    @Html.DisplayFor(m => item.ReadTime)
                </div>
            }                             
            </div>               
     }
</div>
    <div class="tab-pane">
        <h4 class="text-info">Blasts to be delivered</h4>
        @if (Model.UnAnswered.Count == 0)
        {
            @Html.Label("All done!")
        }
        @foreach (var item in Model.UnAnswered)
        {      <div class="table-bordered">
            <div>
                <span class="glyphicon glyphicon-question-sign "></span>
                @Html.DisplayFor(m => item.Question)
                <br />
                @Html.DisplayFor(m => item.SendTime)
            </div>            
        </div>
        }
    </div>
</div>