ServerCode/HealthcareIntervention/Models/AnnouncementMessage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HealthcareIntervention.Models
{
    public class AnnouncementMessage
    {
        
        public int AnnouncementMessageId { get; set; }
        public DateTime Time { get; set; }
        [Display(Name = "Message")]
        public string BlastType { get; set; }
        [Display(Name = "Announcement Name")]
        public string AnnouncementName { get; set; }
        public virtual AnnouncementDay AnnouncementDay { get; set; }

    }
}

ServerCode/HealthcareIntervention/Controllers/AnnouncementMessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HealthcareIntervention.Models;

namespace HealthcareIntervention.Controllers
{
    public class AnnouncementMessagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //GET: AddAnnouncementMessages
        
        // GET: AnnouncementMessages
        public ActionResult Index()
        {
            return View(db.AnnouncementMessages.ToList());
        }

        // GET: AnnouncementMessages/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnnouncementMessage announcementMessage = db.AnnouncementMessages.Find(id);
            if (announcementMessage == null)
            {
                return HttpNotFound();
            }
            return View(announcementMessage);
        }

        // GET: AnnouncementMessages/Create
        public ActionResult Create(int? id)
        {
            if (Session["LoggedUserID"] == null)
            {
                return RedirectToAction("SignOff", "Account");
            }
            AnnouncementMessageViewModel NewMessage = new AnnouncementMessageViewModel();
            NewMessage.AnnouncementDay = (int)id;
            List<SelectListItem> Hours=new List<SelectListItem>();
            List<SelectListItem> Minutes= new List<SelectListItem>();
            for (int i = 1; i <= 12; i++)
            {
                Hours.Add(new SelectListItem
                {
                    Value=i.ToString(),
                    Text=i.ToString()
                });
            }
            for(int i=0;i<60; i+= 5)
            {
                Minutes.Add(new SelectListItem
                {
                    Value = i.ToString(),
                    Text = i.ToString()
                });
            }
            NewMessage.Hours = Hours;
            NewMessage.Minutes = Minutes;
            return View(NewMessage);
        }

        // POST: AnnouncementMessages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( AnnouncementMessageViewModel model)
        {
            if (Session["LoggedUserID"] == null)
            {
                return RedirectToAction("SignOff", "Account");
            }
            if (ModelState.IsValid)
            {
                int StudyId = Convert.ToInt32(Session["StudyId"].ToString());
                AnnouncementMessage announcementMessage = new AnnouncementMessage();
                announcementMessage.AnnouncementName = model.AnnouncementName;
                var Day = db.AnnouncementDays.Where(x => x.StudyPlan.StudyId == StudyId).Where(x => x.DayNo == model.AnnouncementDay).ToList().First();
                announcementMessage.AnnouncementDay = Day;
                announcementMessage.BlastType = model.BlastType;
                var TimeNow = DateTime.Now;
                var hour = (model.AMorPM == "PM") ? 12 + model.Hour : model.Hour;
                hour = (hour > 23) ? 0 : hour;
                var Time = new DateTime(2000,01 ,01,hour, model.Minute, 0);
                announcementMessage.Time = Time;
                db.AnnouncementMessages.Add(announcementMessage);
                db.SaveChanges();
                Day.AnnouncementMessages.Add(announcementMessage);
                db.Entry(Day).State = EntityState.Modified;
                db.SaveChanges();
                switch (model.BlastType)
                {
                    case "TextOnly":
                        return RedirectToAction("Create", "BlastTemplateTextOnly", new { id = announcementMessage.AnnouncementMessageId });
                    case "TextWithResponse":
                        return RedirectToAction("Create", "BlastTemplateTextWithResponse", new { id = announcementMessage.AnnouncementMessageId });                        
                    case "ChooseOneFromList":
                        return RedirectToAction("Create", "BlastTemplateOptionsQuestion", new { id = announcementMessage.AnnouncementMessageId });
                    case "ChooseSeveralFromList":
                        return RedirectToAction("Create", "BlastTemplateOptionsQuestion", new { id = announcementMessage.AnnouncementMessageId });
                    default:
                        break;
                }
            }
            

            return RedirectToAction("GetStudyPlan", "StudyPlans");
        }

        // GET: AnnouncementMessages/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["LoggedUserID"] == null)
            {
                return RedirectToAction("SignOff", "Account");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnnouncementMessage announcementMessage = db.AnnouncementMessages.Find(id);
            if (announcementMessage == null)
            {
                return HttpNotFound();
            }
            return View(announcementMessage);
        }

        // POST: AnnouncementMessages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AnnouncementMessageId,Time,BlastMessage")] AnnouncementMessage announcementMessage)
        {
            if (Session["LoggedUserID"] == null)
            {
                return RedirectToAction("SignOff", "Account");
            }
            if (ModelState.IsValid)
            {
                db.Entry(announcementMessage).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(announcementMessage);
        }

        // GET: AnnouncementMessages/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["LoggedUserID"] == null)
            {
                return RedirectToAction("SignOff", "Account");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AnnouncementMessage announcementMessage = db.AnnouncementMessages.Find(id);
            if (announcementMessage == null)
            {
                return HttpNotFound();
            }
            switch (announcementMessage.BlastType)
            {
                case "TextOnly":
                    var Blast = db.BlastTemplateTextOnlies.Where(x => x.AnnouncementMessageId == announcementMessage.AnnouncementMessageId).ToList().First();
                    db.BlastTemplateTextOnlies.Remove(Blast);
                    db.SaveChanges();
                    break;
                case "TextWithResponse":
                    var Blasts1 = db.BlastTemplateTextWithResponses.Where(x => x.AnnouncementMessageId == announcementMessage.AnnouncementMessageId).ToList();
                    if (Blasts1.Count > 0)
                    {
                        var Blast1 = Blasts1.First();
                        db.BlastTemplateTextWithResponses.Remove(Blast1);
                        db.SaveChanges();
                    }
                    
                    break;
                case "ChooseOneFromList":
                    var Blast2 = db.BlastTemplateOptionses.Where(x => x.AnnouncementMessageId == announcementMessage.AnnouncementMessageId).ToList();
                    foreach(var item in Blast2)
                    {
                        db.BlastTemplateOptionses.Remove(item);
                        db.SaveChanges();
                    }                    
                    break;
                case "ChooseSeveralFromList":
                    var Blast3 = db.BlastTemplateOptionses.Where(x => x.AnnouncementMessageId == announcementMessage.AnnouncementMessageId).ToList();
                    foreach (var item in Blast3)
                    {
                        db.BlastTemplateOptionses.Remove(item);
                        db.SaveChanges();
                    }
                    break;
                default:
                    break;
            }
            
            db.AnnouncementMessages.Remove(announcementMessage);
            db.SaveChanges();
            return RedirectToAction("GetStudyPlan", "StudyPlans");
        }

        // POST: AnnouncementMessages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["LoggedUserID"] == null)
            {
                return RedirectToAction("SignOff", "Account");
            }
            AnnouncementMessage announcementMessage = db.AnnouncementMessages.Find(id);
            db.AnnouncementMessages.Remove(announcementMessage);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ServerCode/HealthcareIntervention/Views/AnnouncementMessages/Create.cshtml
@model HealthcareIntervention.Models.AnnouncementMessageViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Blast Message</h2>

@using (Html.BeginForm("Create", "AnnouncementMessages", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
   
        <hr />
       
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AnnouncementName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnnouncementName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnnouncementName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Time", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-sm-10">
            
                @Html.DropDownListFor(m=>Model.Hour, Model.Hours, new { htmlattributes = new { @class = "btn" } })
                @Html.Label(":mm")
                @Html.DropDownListFor(m => Model.Minute, Model.Minutes, new { htmlattributes = new { @class = "btn" } })
                @Html.Label("AM")
                @Html.RadioButtonFor(m => Model.AMorPM, "AM", new { @checked = true })
                @Html.Label("PM")
                @Html.RadioButtonFor(m => Model.AMorPM, "PM")
              
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlastType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               <div class="list-group">
                   <div class="list-group-item">
                       @Html.RadioButtonFor(model => model.BlastType, "TextOnly", new { @checked = "checked" })
                       @Html.Label("Text Only",new { htmlattributes = new { @class = "list-group-item-text" }})
                   </div>
                   <div class="list-group-item">
                       @Html.RadioButtonFor(model => model.BlastType, "TextWithResponse")
                       @Html.Label("Text With Response", new { htmlattributes = new { @class = "list-group-item-text" } })
                   </div>
                   <div class="list-group-item">
                       @Html.RadioButtonFor(model => model.BlastType, "ChooseOneFromList")
                       @Html.Label("Pick one from a list", new { htmlattributes = new { @class = "list-group-item-text" } })
                   </div>
                   <div class="list-group-item">
                       @Html.RadioButtonFor(model => model.BlastType, "ChooseSeveralFromList")
                       @Html.Label("Pick many from a list", new { htmlattributes = new { @class = "list-group-item-text" } })
                   </div>
               </div>
            </div>
        </div>
        @*@Html.HiddenFor(m => Model.Hours)
        @Html.HiddenFor(m => Model.Minutes)*@
        @Html.HiddenFor(m => Model.AnnouncementDay)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Next" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back", "GetStudyPlan", "StudyPlans")
</div>

ServerCode/HealthcareIntervention/Views/AnnouncementMessages/Delete.cshtml
@model HealthcareIntervention.Models.AnnouncementMessage

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AnnouncementMessage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlastMessage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlastMessage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ServerCode/HealthcareIntervention/Views/AnnouncementMessages/Details.cshtml
@model HealthcareIntervention.Models.AnnouncementMessage

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AnnouncementMessage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlastMessage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlastMessage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AnnouncementMessageId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ServerCode/HealthcareIntervention/Views/AnnouncementMessages/Edit.cshtml
@model HealthcareIntervention.Models.AnnouncementMessage

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AnnouncementMessage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AnnouncementMessageId)

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlastMessage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BlastMessage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlastMessage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ServerCode/HealthcareIntervention/Views/AnnouncementMessages/Index.cshtml
@model IEnumerable<HealthcareIntervention.Models.AnnouncementMessage>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BlastMessage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BlastMessage)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AnnouncementMessageId }) |
            @Html.ActionLink("Details", "Details", new { id=item.AnnouncementMessageId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.AnnouncementMessageId })
        </td>
    </tr>
}

</table>